### ISSUE TITLE
Configurable prefix for test users

### ISSUE THREAD

**Issue by ralphvandenhoudt** [pfaocle/codeception-module-drupal-user-registry#7]
I'd like to have a configurable prefex for the test users instead of 'test.<rolename>'. Is it ok to post a patch for it?

**Comment by pfaocle** [comment]
Of course - should be a simple enough change. Perhaps default to "test." if no custom prefix is configured in the suite configuration.

I would also suggest that we prevent empty prefixes though, to avoid clashing with existing users (e.g. I've seen lots of sites with a user called "administrator" in the "administrator" role!)

**Comment by ralphvandenhoudt** [comment]
I submitted the pull request

**Comment by pfaocle** [comment]
Pull request: https://github.com/pfaocle/codeception-module-drupal-user-registry/pull/8
